# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: &title MDB Training Program
tagline: MDB Training Program
description: A crash course to mobile development, for iOS and React Native.
author: Mobile Developers of Berkeley
baseurl: ''
url: 'https://learn.mdb.dev/'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor/"]
# ga_tracking: UA-175621368-1

# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.3.2
color_scheme: scheme
search_enabled: true
heading_anchors: true
permalink: pretty
footer_content:

# Collections for website data
collections:
  staffers:
  schedules:
  react-native:
    permalink: '/:collection/:path/'
    output: true
  # react-native-sp21:
  #   permalink: '/:collection/:path/'
  #   output: true
  ios:
    permalink: '/:collection/:path/'
    output: true
  # ios-sp21:
  #   permalink: '/:collection/:path/'
  #   output: true
  # ios-fa21:
  #   permalink: '/:collection/:path/'
  #   output: true
  workshops:
    permalink: '/:collection/:path/'
    output: true
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: react-native
    values:
      layout: page
  # - scope:
  #     path: ''
  #     type: react-native-sp21
  #   values:
  #     layout: page
  - scope:
      path: ''
      type: ios
    values:
      layout: page
  # - scope:
  #     path: ''
  #     type: ios-fa21
  #   values:
  #     layout: page
  # - scope:
  #     path: ''
  #     type: ios-sp21
  #   values:
  #     layout: page
  - scope:
      path: ''
      type: workshops
    values:
      layout: page
  - scope:
      path: "assets/images"
    values:
      image: true
# Configure collections for Just the Docs
just_the_docs:
  collections:
    pages:
      name: General
    react-native:
      name: React Native
    # react-native-sp21:
    #   name: React Native Spring 2021 Archive
    ios:
      name: iOS
    workshops:
      name: Workshops
    # ios-fa21:
    #   name: iOS Fall 2021 Archive
    # ios-sp21:
    #   name: iOS Spring 2021 Archive

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
